### PR TITLE
Front page hero minor styling fixes - close #214

### LINKED ISSUE #214: Front Page Hero Desktop
Hero-container:
max-width: 1000px;
margin: 0 auto (Or centered in a way)

h2 {
line-height: 4rem;
}

### PR DESCRIPTION
**Pull request by atfilipcc**
Close #214 
Minor styling fixes
Co-authored-by: Eullin Chang Eullin@users.noreply.github.com

### CODE REVIEW

File: web/src/pages/front-page.tsx [hunk 1]
```diff
@@ -29,8 +29,9 @@ const date = css`
 
 const hero = css`
 	min-height: calc(100vh - 20rem);
+	max-width: 1000px;
 	h2 {
-		line-height: 3.5rem;
+		line-height: 4rem;
```
Comment (boyeborg) [inline web/src/pages/front-page.tsx:34]: Perhaps `1 em` would make more sense here? Then it's dependent on its own font size, making it more flexible.

**Review by hexjelly — APPROVED** [review]
