### PR TITLE
fix: update articles page design

### LINKED ISSUE #200: Update articles page design
There's a few small changes to the article list page:

- Move content below hero
- Use the new hero scroll button option
- Create a "load more" button that will load more articles when pressed, showing a default of ... there's 3 in the design, but I imagine it's more for illustration purposes, and we probably want to load at least a few more by default?
- Date headers should use long form date names instead of just numbers

image

### PR DESCRIPTION
**Pull request by Eullin**
We are currently showing 3 articles at the time. If we would have much more articles to display we would have to reconsider this solution since it won't be efficient. 

Closes #200

### CODE REVIEW

File: web/src/pages/article-overview.tsx [hunk 1]
```diff
@@ -129,8 +162,10 @@ const ArticleOverview: React.FC<Props> = () => {
 
 			<div css={body}>
 				{articles && articles.length > 0 ? (
-					articles?.map(art => {
+					articles?.map((art, i) => {
+						console.log(art.title.no, art.publishedAt);
```
Comment (hexjelly) [inline web/src/pages/article-overview.tsx:166]: Let's remove this `console.log` 😇

File: web/src/pages/article-overview.tsx [hunk 2]
```diff
@@ -129,8 +162,10 @@ const ArticleOverview: React.FC<Props> = () => {
...
 						// Try using publishedAt date if it exists first, otherwise fall back to _createdAt date
+						if (i >= numberOfArticles) return;
```
Comment (hexjelly) [inline web/src/pages/article-overview.tsx:168]: I think a slightly more idiomatic approach might be to do a `.slice(0, numberOfArticles)` on the `articles` array before the `.map` call. But not very important to change.

File: web/src/pages/article-overview.tsx [hunk 3]
```diff
@@ -163,6 +198,16 @@ const ArticleOverview: React.FC<Props> = () => {
 				) : (
 					<p>Ingen artikler enda</p>
 				)}
+				<div css={buttonWrapper}>
+					<button
```
Comment (hexjelly) [inline web/src/pages/article-overview.tsx:202]: I guess in theory we should also check if we actually have any more articles, and disable (probably rather hide?) the button when we reached the end.

Something like `{ articles.length >= numberOfArticles && <button .... stuff }` maybe.

**Review by hexjelly — APPROVED** [review]
